Lots of cleanup and documentation

diff --git a/travis-run b/travis-run
--- a/travis-run
+++ b/travis-run
@@ -19,24 +19,95 @@
 . $(dirname $0)/common.sh
 
 usage () {
-    echo "Usage: $0 [OPTIONS...] -- [BACKEND_ARGS]">&2
-    echo "Options:">&2
+    echo "Usage: $0 [OPTIONS..] [BACKEND_OPTIONS..] [COMMAND [ARGS..]]"
+    echo "Global Options (OPTIONS):"
 
-    echo "\t-k, --keep">&2
-    echo "\t\tPreserve schroot after build finishes. This is useful">&2
-    echo "\t\tduring development as you will only have to install">&2
-    echo "\t\tbuild-depends once. Make sure your build server cleans stale">&2
-    echo "\t\tschroot sessions every once in a while.">&2
-    echo >&2
+    echo "\t-b, --backend=BACKEND"
+    echo "\t\tVirtualization backend to use. Currently avalialbe backends:"
+    echo "\t\t  $(echo $BACKENDS | sed 's/ /, /g')"
+    echo "\t\t(defaults to: vagrant)"
 
-    echo "\t-b, --backend=BACKEND">&2
-    echo "\t\tUse specified virtualization backend on the server. Currently">&2
-    echo "\t\tavalialbe backends: $(echo $BACKENDS | sed 's/ /, /g')">&2
-    echo "\t\t(defaults to: schroot)">&2
+    echo "\t-k, --keep"
+    echo "\t\tDo not stop and destroy VM after build finishes. This is useful"
+    echo "\t\tduring development as you will only have to go through"
+    echo "\t\tVM creation once. Make sure to \`travis-run clean' or"
+    echo "\t\t\`travis-run stop' after you're done with the VM."
+
+    echo "\t-n, --vm-name=VM_NAME"
+    echo "\t\tArbitrary identifier associated with the build VM. (defaults"
+    echo "\t\tto: travis-run-vm). The backend may support persistent options"
+    echo "\t\tper VM referenced by name, see backend documentation for "
+    echo "\t\tdetails."
+    echo
+    echo
+
+    echo "Global Backend Options (BACKEND_OPTIONS):"
+    echo "\tNone so far, see Commands for command specific backend options."
+    echo
+    echo
+
+    echo "Commands (COMMAND):"
+    echo "\trun (default if no command given)"
+    echo "\t\tRun the build matrix in sequence and abort on the first failure"
+    echo "\t\tdropping into a shell for diagnostics by default. Note that by"
+    echo "\t\tdefault the project directory is also synchronized with the VM"
+    echo "\t\trunning the build before and after the build so make sure your"
+    echo "\t\t.travis.yml contains a \`clean' action before attempting the"
+    echo "\t\tbuild."
+    echo
+    echo "\t\tBackend Options for \`schroot':"
+    echo "\t\t\t--schrot-user=USER"
+    echo "\t\t\t\tName of the user to run commands inside the"
+    echo "\t\t\t\tchroot as, see -u option of the \`schroot'"
+    echo "\t\t\t\tcommand."
+    echo
+    echo
+
+    echo "\tstop"
+    echo "\t\tStop running build VM. This will tear down the VM as well as"
+    echo "\t\tall it's disk state."
+    echo
+    echo
+
+    echo "\tcreate"
+    echo "\t\tSetup build VM. Depending on the backend it might be stored"
+    echo "\t\tglobally or in \`.travis-run' in the current directory."
+    echo "\t\tBackend Options for \`schroot':"
+    echo "\t\t\t--schrot-user=USER"
+    echo "\t\t\t\tName of the user outside the schroot that will"
+    echo "\t\t\t\trun \`travis-run'. This is needed for file"
+    echo "\t\t\t\tsync to work. (required)"
+    echo "\t\tBackend Options for \`vagrant':"
+    echo "\t\t\t--vagrant-docker-from=BASE_IMAGE"
+    echo "\t\t\t\tDocker image to use as the base for the"
+    echo "\t\t\t\tcontainer, see \`FROM' Dockerfile command."
+    echo "\t\t\t\t(defaults to: ubuntu:presice)"
+    echo
+    echo
+
+    echo "\tclean"
+    echo "\t\tStop running build VM, and clean any backend specific state "
+    echo "\t\tkept in the project directory."
+    echo
 }
 
-OPTS=$(getopt -o hkn:c:b: --long help,keep,vm-name,chroot:,backend: -n "$(basename $0)" -- "$@")
+TRAVIS_GETOPT_LONG="help,keep,vm-name,chroot:,backend:"
+TRAVIS_GETOPT_SHORT="hkn:c:b:"
+
+if [ "$BACKEND_GETOPT_LONG" ]; then
+    LONGOPTS="$TRAVIS_GETOPT_LONG,$BACKEND_GETOPT_LONG"
+else
+    LONGOPTS="$TRAVIS_GETOPT_LONG"
+fi
+
+OPTS=$(getopt \
+    -o "$TRAVIS_GETOPT_SHORT" \
+    --long "$LONGOPTS" \
+    -n "$(basename $0)" -- "$@")
+
 eval set -- "$OPTS"
+
+BACKEND_ARGS=""
 
 while true; do
     case "$1" in
@@ -45,76 +116,35 @@ while true; do
         -n|--vm-name) OPT_VM_NAME=$2; shift; shift ;;
         -b|--backend) OPT_BACKEND=$2; shift; shift ;;
 
+	--schroot-*|--vagrant-*)
+	    BACKEND_ARGS="$BACKEND_ARGS $1 $2"; shift; shift ;;
+
         --) shift; break ;;
         *) echo "Error parsing argument: $1">&2; exit 1 ;;
     esac
 done
 
-BACKEND_ARGS="$@"
+## Global Options
 
 # OPT_KEEP unset by default
 OPT_VM_NAME=${OPT_VM_NAME:-travis-run-amd64}
-OPT_BACKEND=${OPT_BACKEND:-schroot}
+OPT_BACKEND=${OPT_BACKEND:-vagrant}
 
-if [ ! -e .travis.yml ]; then
-    echo "Error: .travis.yml does not exist.">&2
-    exit 1
+## Commands
+
+if [ "$1" ]; then
+    COMMAND=$1; shift
+else
+    COMMAND="run"
 fi
 
-if [ ! $OPT_KEEP ]; then
-    trap "backend_end $OPT_VM_NAME" 0 2 15
-fi
-
-backend_init "$OPT_VM_NAME"
-
-if [ $? -ne 0 ]; then
-    echo "Starting VM failed">&2
-    exit 1
-fi
-
-RUN="backend_run $OPT_VM_NAME copy $@"
-RUN_nocopy="backend_run $OPT_VM_NAME nocopy $@"
-
-run_tests () {
-    (
-	# echo 'travis_run_onexit () {'
-	# echo 'RV=$?'
-	# echo 'if [ $RV -ne 0 ]; then
-        #    env | awk -v FS="=" '"'"'{ print "export " $1 "=\"" $2 "\"" }'"'"' >> ~/.bashrc;
-        #    exit $RV
-        # fi'
-	# echo '}'
-	# echo 'trap "travis_run_onexit" 0 2 15'
-
-	echo "cd build"
-	printf "%s\n" "$1" | $(dirname $0)/travis-run-script --build
-    ) | $RUN -- bash # travis-build seems to assume bash :/
-
-    if [ $? -ne 0 ]; then
-    	echo "Build failed, please investigate." >&2
-    	if [ x"$OPT_BACKEND" = x"vagrant" ]; then
-    	    $RUN_nocopy
-    	else
-    	    $RUN_nocopy -- bash
-    	    exit
-    	fi
-    fi
-}
-
-cfgs=$($(dirname $0)/travis-run-script)
-BIFS=$IFS; IFS="\n"
-for cfg in "$cfgs"; do
-    IFS=$BIFS run_tests "$cfg"
-done
-IFS=$BIFS
-
-# # TODO: get --exclude's from .gitignore
-# rsync -e "$(which ssh) $SSH_OPTS" -lEr --chmod=775 \
-#     --rsync-path="sudo -u travis rsync" \
-#     --exclude='/.cabal-sandbox/*' \
-#     --exclude='/cabal.sandbox.config' \
-#     --exclude='dist/*' \
-#     --exclude='.git/*' \
-#     --delete \
-#     --delete-excluded \
-#     ./ "$server:/home/travis/$(strip_home $PWD)"
+case "$COMMAND" in
+    run)    ( . $(dirname $0)/travis-run-run.sh    );;
+    stop)   ( backend_end $OPT_VM_NAME             );;
+    create) ( . $(dirname $0)/travis-run-create.sh );;
+    clean)  ( . $(dirname $0)/travis-run-clean.sh  );;
+    *)
+	echo "Error: unknown command \"$COMMAND\"">&2
+	echo "See \`$0 --help' for a list of valid commands"
+	exit 1
+esac
