Add `--shell` option to `run` command

diff --git a/travis-run b/travis-run
--- a/travis-run
+++ b/travis-run
@@ -54,6 +54,10 @@ run [BUILD_ID | BUILD_CONFIG]:\n\
 	dropped into a shell inside the build environment so you can figure \n\
 	out what's going on.\n\
 \n\
+		--shell\n\
+			Prepare for a build but instead of running it launch a\n\
+			shell.\n\
+\n\
 \n\
 stop:\n\
 	Stop running build VM. This will tear down the VM as well as all it's\n\
@@ -100,7 +104,7 @@ matrix:
 #				sync to work. (required)"
 }
 
-TRAVIS_GETOPT_LONG="help,keep,vm-name,backend:"
+TRAVIS_GETOPT_LONG="help,keep,vm-name,backend:,shell"
 TRAVIS_GETOPT_SHORT="hkn:b:"
 
 if [ "$BACKEND_GETOPT_LONG" ]; then
@@ -136,6 +140,8 @@ while true; do
         -n|--vm-name) OPT_VM_NAME=$2; shift; shift ;;
         -b|--backend) OPT_BACKEND=$2; shift; shift ;;
 
+        --shell)      OPT_SHELL=1; shift ;;
+
 	--schroot-*|--vagrant-*|--docker-*)
 	    if takes_opt "$1"; then
 		backend_args_append "$1 $2"
@@ -166,6 +172,11 @@ if [ "$1" ]; then
     COMMAND=$1; shift
 else
     COMMAND="run"
+fi
+
+if [ "$OPT_SHELL" ] && [ x"$COMMAND" != x"run" ]; then
+    error "Error: Command \`$COMMAND' does not take option \`--shell'"
+    exit 1
 fi
 
 case "$COMMAND" in
